let images = `ADC-alt.svg	DGB.svg		IOTA-alt.svg	OMNI.svg	STRAT.svg
ADC.svg		DGD.svg		IOTA.svg	OPAL-alt.svg	SWIFT-alt.svg
AEON-alt.svg	DGX.svg		JBS-alt.svg	OPAL.svg	SWIFT.svg
AEON.svg	DMD-alt.svg	JBS.svg		PART-alt.svg	SYNC-alt.svg
AMP-alt.svg	DMD.svg		KMD-alt.svg	PART.svg	SYNC.svg
AMP.svg		DOGE-alt.svg	KMD.svg		PIGGY-alt.svg	SYS-alt.svg
ANC-alt.svg	DOGE.svg	KOBO.svg	PIGGY.svg	SYS.svg
ANC.svg		EMC-alt.svg	KORE-alt.svg	PINK-alt.svg	TRIG-alt.svg
ARCH-alt.svg	EMC.svg		KORE.svg	PINK.svg	TRIG.svg
ARCH.svg	EOS-alt.svg	LBC-alt.svg	PIVX-alt.svg	TX-alt.svg
ARDR-alt.svg	EOS.svg		LBC.svg		PIVX.svg	TX.svg
ARDR.svg	ERC-alt.svg	LDOGE-alt.svg	POT-alt.svg	UBQ-alt.svg
AUR-alt.svg	ERC.svg		LDOGE.svg	POT.svg		UBQ.svg
AUR.svg		ETC-alt.svg	LISK-alt.svg	PPC-alt.svg	UNITY-alt.svg
BANX-alt.svg	ETC.svg		LISK.svg	PPC.svg		UNITY.svg
BANX.svg	ETH-alt.svg	LTC-alt.svg	QRK-alt.svg	USDT-alt.svg
BAT-alt.svg	ETH.svg		LTC.svg		QRK.svg		USDT.svg
BAT.svg		FC2-alt.svg	MAID-alt.svg	RADS-alt.svg	VIOR-alt.svg
BAY-alt.svg	FC2.svg		MAID.svg	RADS.svg	VIOR.svg
BAY.svg		FCT-alt.svg	MCO-alt.svg	RBIES-alt.svg	VNL-alt.svg
BC-alt.svg	FCT.svg		MCO.svg		RBIES.svg	VNL.svg
BC.svg		FLO-alt.svg	MINT-alt.svg	RBT-alt.svg	VPN-alt.svg
BCC-alt.svg	FLO.svg		MINT.svg	RBT.svg		VPN.svg
BCC.svg		FRK-alt.svg	MONA-alt.svg	RBY-alt.svg	VRC-alt.svg
BCN-alt.svg	FRK.svg		MONA.svg	RBY.svg		VRC.svg
BCN.svg		FTC-alt.svg	MRC.svg		RDD-alt.svg	VTC-alt.svg
BFT-alt.svg	FTC.svg		MSC-alt.svg	RDD.svg		VTC.svg
BFT.svg		GAME-alt.svg	MSC.svg		REP-alt.svg	WAVES-alt.svg
BRK-alt.svg	GAME.svg	MTR-alt.svg	REP.svg		WAVES.svg
BRK.svg		GDC-alt.svg	MTR.svg		RISE-alt.svg	XAI-alt.svg
BRX-alt.svg	GDC.svg		MUE-alt.svg	RISE.svg	XAI.svg
BRX.svg		GEMZ-alt.svg	MUE.svg		SAR-alt.svg	XBS-alt.svg
BSD-alt.svg	GEMZ.svg	NBT.svg		SAR.svg		XBS.svg
BSD.svg		GLD-alt.svg	NEO-alt.svg	SCOT-alt.svg	XCP-alt.svg
BTA.svg		GLD.svg		NEO.svg		SCOT.svg	XCP.svg
BTC-alt.svg	GNO-alt.svg	NEOS-alt.svg	SDC-alt.svg	XEM-alt.svg
BTC.svg	GNO.svg		NEOS.svg	SDC.svg		XEM.svg
BTCD-alt.svg	GNT-alt.svg	NEU-alt.svg	SIA-alt.svg	XMR.svg
BTCD.svg	GNT.svg		NEU.svg		SIA.svg		XPM-alt.svg
BTS-alt.svg	GOLOS-alt.svg	NLG-alt.svg	SJCX-alt.svg	XPM.svg
BTS.svg		GOLOS.svg	NLG.svg		SJCX.svg	XRP-alt.svg
CLAM-alt.svg	GRC-alt.svg	NMC-alt.svg	SLG-alt.svg	XRP.svg
CLAM.svg	GRC.svg		NMC.svg		SLG.svg		XTZ-alt.svg
CLOAK-alt.svg	GRS.svg		NOTE-alt.svg	SLS-alt.svg	XTZ.svg
CLOAK.svg	HEAT-alt.svg	NOTE.svg	SLS.svg		XVG-alt.svg
DAO-alt.svg	HEAT.svg	NVC-alt.svg	SNRG-alt.svg	XVG.svg
DAO.svg		ICN-alt.svg	NVC.svg		SNRG.svg	YBC-alt.svg
DASH-alt.svg	ICN.svg		NXT-alt.svg	START-alt.svg	YBC.svg
DASH.svg	IFC-alt.svg	NXT.svg		START.svg	ZEC-alt.svg
DCR-alt.svg	IFC.svg		OK-alt.svg	STEEM-alt.svg	ZEC.svg
DCR.svg		INCNT-alt.svg	OK.svg		STEEM.svg	ZEIT-alt.svg
DCT-alt.svg	INCNT.svg	OMG-alt.svg	STR-alt.svg	ZEIT.svg
DCT.svg		IOC-alt.svg	OMG.svg		STR.svg
DGB-alt.svg	IOC.svg		OMNI-alt.svg	STRAT-alt.svg`;
